title: Structured Techniques for Algorithmic Robotics (STAR) Lab
short_title: STAR Lab
name: Structured Techniques for Algorithmic Robotics (STAR) Lab
description: The STAR Lab at Georgia Tech develops structured computational and learning frameworks for reliable, efficient, and generalizable robots.
url: https://gt-star-lab.github.io
baseurl: ""

markdown: kramdown
permalink: /:categories/:title/
future: true
sass:
  sass_dir: css
  style: compressed

exclude:
  - "*.branches"
  - "*.class"
  - "*.cpp"
  - "*.csv"
  - "*.fasta"
  - "*.gz"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.nb"
  - "*.newick"
  - "*.nex"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.tiff"
  - "*.tips"
  - "*.trees"
  - "*.tsv"
  - "*.txt"
  - "*.xml"
  - "*.zip"
  - ".jekyll-cache"
  - ".sass-cache"
  - "_site"
  - "Gemfile"
  - "Gemfile.lock"
  - "*.DS_Store"
